# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'F82017' do
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.1'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for F82017
  pod 'FBSDKShareKit'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

  platform :ios, '9.0'
  target 'F82017-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    #pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  end

  target 'F82017Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
