# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'F82017' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for F82017
  pod 'FBSDKShareKit'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

  target 'F82017-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'F82017Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
